#!/bin/sh
__date() { date "+%F %X%z %Z"; }
LC_TIME=ru_RU.UTF-8 TZ=Europe/Moscow __date
LC_TIME=en_GB.UTF-8 TZ=America/New_York __date
LC_TIME=es_ES.UTF-8 TZ=America/Asuncion __date
LC_TIME=es_ES.UTF-8 TZ=America/Argentina/Buenos_Aires __date
