name: flake-check
on: [push, pull_request]
jobs:
  nix_parsing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - name: Check
        run: |
          nix flake check
